name = "gurblecraft"
author = "gurble"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8502a7317862d44cde3012665d75e0f94623b5d2764603d9261ae043069b6672"

[versions]
fabric = "0.19.2"
minecraft = "1.20.1"

[options]
acceptable-game-versions = []
