name = "gurblecraft"
author = "gurble"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8cf8200bbe3ae1ca15967795334a29068ef53b271d98ffa0e2c074b221ec4758"

[versions]
fabric = "0.19.2"
minecraft = "1.20.1"

[options]
acceptable-game-versions = []
