name = "gurblecraft"
author = "gurble"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "072ee6f9cfa806398d48652cd13b34231220a0a483923059c722ee6dcfadc8d8"

[versions]
fabric = "0.19.2"
minecraft = "1.20.1"

[options]
acceptable-game-versions = []
